Update meeting dropdown
codeforsanjose/project-happening-atm pull request #289
Opened 2022-07-30 15:50 UTC by Savimaster

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)

Added the meeting dropdown to change meeting status

- Describe what changes are being made

Added mutation for updating a meeting and getting a meeting. Also added constants for meeting status. I also updated validators.js so I could update some parts, without having to provide everything. Finally, I added to Header.jsx and created a simple Dropdown component as the Meeting dropdown.

- Describe why these changes are being made

To allow me to update the meeting status in the backend and in the frontend

- List the use cases and edge cases relevant to this PR

I did not add css for the different meeting statuses

- Describe how errors will be handled. How will we know if this code breaks in production

We will know if the code breaks if no meeting status is shown, and it is an empty box, or if the meeting status does not change when you select a different meeting status in the dropdown

- Describe any external libraries/dependencies added or removed in this PR

None I think

- Describe any security risks are there regarding this change

None I think

- Describe how you tested these changes

I tested selecting different meeting statuses and watching it change in the frontend and in the backend through graph ql playground. I also tested that it changed by updating agenda items and watching the meeting status change in accordance to it

- Link to relevant external documentation

None

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [ ] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2022-07-31 00:33 UTC, JMStudiosJoe commented on .vscode/settings.json
> +}
need end of file new line please

2022-07-31 00:34 UTC, JMStudiosJoe commented on frontend/src/components/Header/Header.jsx
> +                  {/* Could change these lines to a for loop looping through the statuses json */}
Would that for loop be constantly running? that would be expensive and bog down the ui

2022-07-31 00:35 UTC, JMStudiosJoe commented on frontend/src/constants/MeetingStates.js
> +
same here

2022-07-31 00:36 UTC, JMStudiosJoe commented on frontend/src/graphql/graphql.js
> +export const GET_MEETING = gql`
lets break these querys/mutations into their own files, right now with Evelyns PR is also having changes in this file and will cause confilicts if one merged before the other. A small refactor :)

2022-07-31 00:36 UTC, JMStudiosJoe requested changes
Looking great so far, some minor changes and one question

2022-07-31 05:46 UTC, Savimaster commented on frontend/src/components/Header/Header.jsx
> +                  {/* Could change these lines to a for loop looping through the statuses json */}
Sorry, I didn't mean a for loop, I mean that instead of having four or five different lines for every status, we could map through the statuses list of key pairs and create spans with the labels and values to reduce queues. But atm, I didn't want to overcomplicate things, so I just left the comment in there for a suggestion on maybe reducing the number of necessary lines of code.

2022-07-31 05:47 UTC, Savimaster commented on .vscode/settings.json
> +}
Should I add a new line at the end of the file?

2022-07-31 05:47 UTC, Savimaster commented on frontend/src/constants/MeetingStates.js
> +
Could you clarify what same here refers to?

2022-07-31 05:48 UTC, Savimaster commented on frontend/src/graphql/graphql.js
> +export const GET_MEETING = gql`
So then, should I make the two different files, or is that something we should maybe do later? Because if I create two separate files there will be more merge conflicts

2022-08-09 19:46 UTC, JMStudiosJoe commented on frontend/src/graphql/graphql.js
> +export const GET_MEETING = gql`
no, if you make a new file for your gql querys to go into, that should avoid the conflicts. 1 file for the queries that all relate to each other instead of all queries in one file, that will lead to the conflicts.

2022-08-09 19:53 UTC, JMStudiosJoe reviewed
just one minor refactor to move the queries to their own file and we can merge :)

2022-08-18 20:57 UTC, JMStudiosJoe approved these changes
Good on the refactor, but the queries you over did it a bit and the rename to just query or mutation is also not the best, i was thinking even more declarative, more specific so would be like userAccountQueriesMutations, meetingitemQueriesMutations which will make the gql functionality much easier to debug and read. but that can be another PR

2022-08-18 20:57 UTC, JMStudiosJoe commented
ok ya small conflict in graphql.js :) resolve that then can merge

2022-08-29 19:24 UTC, JMStudiosJoe submitted a review, later dismissed
lgtm

2022-08-30 23:25 UTC, JMStudiosJoe commented
able to fix the conflicts and get merged? let me konw if want to connect to go over them.

2022-08-31 07:34 UTC, Savimaster commented
> able to fix the conflicts and get merged? let me konw if want to connect to go over them.

@JMStudiosJoe, I don't think I can fix the merge conflicts because I can't review and merge my PR, so it doesn't allow me to resolve the merge conflicts. The merge conflicts come from the fact that I deleted the graphql.js file to make two new files with the mutations and queries. I think that it is okay to merge the two files instead of adding specific files with queries and mutations because that may be a change that should be done in a separate PR.

2022-09-04 02:36 UTC, merged