Evelynsbranch
codeforsanjose/project-happening-atm pull request #290
Opened 2022-07-30 17:41 UTC by ENguyen25

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
Added feature to update user info

- Describe what changes are being made
Added mutations for admin and user to update their phone number and email (if using sign-up option)

- Describe why these changes are being made

- List the use cases and edge cases relevant to this PR

- Describe how errors will be handled. How will we know if this code breaks in production

- Describe any external libraries/dependencies added or removed in this PR

- Describe any security risks are there regarding this change

- Describe how you tested these changes

- Link to relevant external documentation

--------------------------
### :clipboard: Mandatory Checklist

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2022-07-31 00:15 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/controllers/uploadController.js
> +      console.log('hello')
lets remove the console log please

2022-07-31 00:16 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/controllers/zoomController.js
> +const axios = require('axios');
also we should refactor this into its own file so the common methods can be called and correct headers always applied. This would be a great chance to do the refactor as well :)

2022-07-31 00:17 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/controllers/zoomController.js
> +    const email = 'enguyen6208@gmail.com'; //host email id
this should be an env var or also come from the request?

2022-07-31 00:18 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/controllers/zoomController.js
> +      headers: {
ya these are all too common headers lets refactor and only for this file no need to go back to any others doing this, yet.

2022-07-31 00:18 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/controllers/zoomController.js
> +}
need EOF space

2022-07-31 00:19 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/utilities/auth.js
> +module.exports = { addToken }
need EOF new line

2022-07-31 00:19 UTC, JMStudiosJoe commented on backend/agenda_upload_service/lambda/utilities/config.js
> +module.exports = config[env]
same

2022-07-31 00:22 UTC, JMStudiosJoe commented on frontend/src/components/LoginHandler/LoginHandler.jsx
> +      window.localStorage.setItem("email_address", userName)
I would also like any logic that manipulates the window object also refactored to its own file so all the window manipulation only happens in one place. It would be the same as the axios refactoring so all the axios calls will only be in one file so if we need to swap it to another library its only in one place to change :)

2022-07-31 00:23 UTC, JMStudiosJoe commented on frontend/src/components/TermsOfUse/TermsOfUse.jsx
> +        Please note that this Use Policy is subject to change without notice,
lets refactor this Terms of Use HTML block into its own file that way much easy to do for different languages or a good step for handling new languages.

2022-07-31 00:25 UTC, JMStudiosJoe commented on frontend/src/components/UpdateUserInfo/UpdateUserEmail.jsx
> +    verifyEmailAddressFormat();
this is well a not so great function. lets make a pure function that takes in a parameter of the email and returns a boolean if good or not. this will allow us to use in other places as well.

2022-07-31 00:26 UTC, JMStudiosJoe commented on frontend/src/components/UpdateUserInfo/UpdateUserEmail.jsx
> +  const verifyEmailAddressFormat = () => {
lets make this function take in the new email and return if good or not, then set the errors in `setFieldErrors`

2022-07-31 00:26 UTC, JMStudiosJoe commented on frontend/src/components/UpdateUserInfo/UpdateUserNumber.jsx
> +    verifyPhoneNumberFormat();
same for this function

2022-07-31 00:27 UTC, JMStudiosJoe commented on frontend/src/components/UserAccountView/UserAccountView.jsx
> +        {/* <label htmlFor="firstname">
lets remove the commentd out code if it no longer needed

2022-07-31 00:28 UTC, JMStudiosJoe commented on frontend/src/constants/Recaptchas.js
> +  ACCOUNT_CREATION: '6LdQw4IeAAAAAJhBO-s9vuYjuHXCrPUyw_OTa5hP',
is this ok to be going in or no?

2022-07-31 00:32 UTC, JMStudiosJoe requested changes
Looking great so far and fantastic refactoring opportunity that shouldnt be too difficult and really help clean things up :) great work.

2022-07-31 00:38 UTC, JMStudiosJoe commented on frontend/src/graphql/graphql.js
> +export const UPDATE_EMAIL = gql`
lets add the user details kinda quersies/mutations to their own file so much easier to track and debug and less conflicts since if we merge this or the other open pr then there will be conflicts since you both have changes here. :) a small refactor as well

2022-08-18 01:49 UTC, ENguyen25 commented on frontend/src/components/LoginHandler/LoginHandler.jsx
> +      window.localStorage.setItem("email_address", userName)
ack

2022-08-18 01:53 UTC, ENguyen25 commented on frontend/src/components/UserAccountView/UserAccountView.jsx
> +        {/* <label htmlFor="firstname">
ack

2022-08-18 02:12 UTC, ENguyen25 commented on frontend/src/components/TermsOfUse/TermsOfUse.jsx
> +        Please note that this Use Policy is subject to change without notice,
ack

2022-08-18 02:14 UTC, ENguyen25 commented on frontend/src/constants/Recaptchas.js
> +  ACCOUNT_CREATION: '6LdQw4IeAAAAAJhBO-s9vuYjuHXCrPUyw_OTa5hP',
ack

2022-08-18 02:21 UTC, ENguyen25 commented on frontend/src/graphql/graphql.js
> +export const UPDATE_EMAIL = gql`
ack

2022-08-18 20:52 UTC, JMStudiosJoe approved these changes
looks good should have another pr for specific cleanup

2022-08-18 20:52 UTC, merged