Css
codeforsanjose/project-happening-atm pull request #294
Opened 2022-08-27 00:25 UTC by gomezbiggeri

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
Worked on CSS and JSX files to match Figma designs and remove some old legacy features.

- Describe what changes are being made
Changes to the login page, footer, admin Calendar page, and upload modal. 

- Describe why these changes are being made
UI/UX improvements

- List the use cases and edge cases relevant to this PR
N/A

- Describe how errors will be handled. How will we know if this code breaks in production
N/A

- Describe any external libraries/dependencies added or removed in this PR
N/A

- Describe any security risks are there regarding this change
N/A

- Describe how you tested these changes
Docker local environment

- Link to relevant external documentation
N/A

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x ] Have you discussed these changes with the project leader(s)?
- [x ] Do all variable and function names communicate what they do?
- [ x] Were all the changes commented and / or documented?
- [ ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2022-08-27 20:38 UTC, JMStudiosJoe requested changes
Just some small questions and some minor cleanup before merging... also only about half way done will review finish later.

2022-08-27 20:38 UTC, JMStudiosJoe commented on frontend/src/components/CSVUploadModal/CSVUploadModal.scss
> +      // border: 4px solid transparent;
Let's remove the commented out code please

2022-08-27 20:38 UTC, JMStudiosJoe commented on frontend/src/components/CSVUploadModal/CSVUploadModal.scss
> +      display: flex;
I'm not much of a fan of display flex but I know it has its uses in smaller areas. Have you used css grid before? But this use case does look like a small one.

2022-08-27 20:38 UTC, JMStudiosJoe commented on frontend/src/components/LoginHandler/LoginHandler.scss
> -                    font-size:1.5rem;
Hmmm why going from rem to px? I thought best practices were to be moving from px to rem and vw?

2022-08-29 00:52 UTC, gomezbiggeri commented on frontend/src/components/CSVUploadModal/CSVUploadModal.scss
> +      // border: 4px solid transparent;
removed commented line

2022-08-29 00:54 UTC, gomezbiggeri commented on frontend/src/components/CSVUploadModal/CSVUploadModal.scss
> +      display: flex;
I have, but not as much as flex, and I was having difficulty getting this one right.

2022-08-29 00:57 UTC, gomezbiggeri commented on frontend/src/components/LoginHandler/LoginHandler.scss
> -                    font-size:1.5rem;
I did this before learning about rem. I'll fix it.

2022-08-29 03:32 UTC, gomezbiggeri reviewed
I kept the updated loginContext function, and added my current design layout.

2022-08-30 23:22 UTC, JMStudiosJoe commented on frontend/src/components/MeetingListView/MeetingListItem.jsx
> +  //LOCALDEV Hardcoded status for styling <----- REMOVE BEFORE COMMITING
Remove before commiting?

2022-08-30 23:23 UTC, JMStudiosJoe commented on frontend/src/components/MeetingListView/MeetingListItem.scss
> +    // grid-template-columns: 1.4em 2fr 2fr 1.4em;
can remove the commented out code as well here

2022-08-30 23:23 UTC, JMStudiosJoe commented on frontend/src/components/MeetingListView/MeetingListItem.scss
> +      // grid-column: 2 / 3;
these as well

2022-08-30 23:24 UTC, JMStudiosJoe reviewed
just some minor cleanup then good to go

2022-09-08 22:45 UTC, closed without merging