Update meeting statuses
codeforsanjose/project-happening-atm pull request #336
Opened 2023-08-04 22:05 UTC by jerrycyip

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
  - Update Meeting Agenda Header and dropdown functionality for admin and community users to more closely match latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0)

- Describe what changes are being made
  - As per general description above, the meeting agenda header and dropdown meeting status selector has been updated to more closely match the latest MVP designs including: 
    -  better desktop and mobile layout, with streamlined meeting header details and internationalization (multi-language) support
    - a new re-usable dropdown component for Admin user's updates to overall meeting status.  Note, the new dropdown component enables re-use for future implementation of Admin user's "meeting item status" dropdown selector.
    - Note, the new dropdown reflects the new meeting status selection values per the latest MVP designs (i.e. Upcoming / In Progress / In Recess / Ended / Deferred), effectively replacing the old meeting status values (i.e. Not Started / In Progress / Ended / Cancelled)  
    - corresponding display of meeting status to community users (i.e. without the Admin dropdown selector)
    
- Describe why these changes are being made
  - Updates to more closely match latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0)

- List the use cases and edge cases relevant to this PR
  - As per latest MVP designs mentioned above.

- Describe how errors will be handled. How will we know if this code breaks in production
  - N/A

- Describe any external libraries/dependencies added or removed in this PR
  - N/A
- Describe any security risks are there regarding this change
  - N/A

- Describe how you tested these changes
  - Regression tested functionality on frontend before and after code changes.
  - Note, during initial testing identified pre-existing bugs that will likely require addressing in the future as follows:
    1.) When an admin updates the meeting status on the individual meeting page and subsequently returns to the Meeting List page, the status of the updated meeting doesn’t immediately update and instead users must refresh the page.  
    2.) Current functionality does not allow an Admin user to change the overall Meeting status back to Upcoming once it's any other state (e.g. In Progress etc.)

- Link to relevant external documentation
  - See latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0)

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before
Admin user prior to changes:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/a7fdc2b7-bad6-4ab8-ab64-02f7439d5698

Community user prior to changes:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/b44d80b7-8ec6-4555-87b4-4b264029320c

#### After
Admin user after changes:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/ab663ca8-aae1-45dc-ac90-f4d910d61db5

Community user after changes:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/7644ed93-f016-429f-b211-26756b6f7758

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2023-08-11 00:06 UTC, JMStudiosJoe commented on frontend/src/components/Dropdown/Dropdown.jsx
> +      <div
gorgeous i love it

2023-08-11 00:07 UTC, JMStudiosJoe commented on frontend/src/components/Dropdown/Dropdown.jsx
> +            value.value.toLowerCase().split(" ").join("-"),
this feels a little strange extra to me can you go into more details?

2023-08-11 00:18 UTC, JMStudiosJoe requested changes

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/Dropdown/Dropdown.scss
> +		overflow: hidden; // ensure rounded edges
rounded edges is just border radius right?  also can we fix the spacing in the file seems quite excessive.

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/Dropdown/Dropdown.scss
> +		// border:1px solid $pendingBlueBackground;
lets remove the unecessary comments like this one, im not sure on all of them but this is defeinitely one we can remove

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/Dropdown/Panel.jsx
> +/*
for me this file feels somehow like an unecessary absstraction layer but im unsure with a tired brain to fully see it but leaving for now. Just want to make a note of it if i come back to this pr with future Joey

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/MeetingHeader/MeetingHeader.jsx
> +    <div className={classnames("meeting-header")}>
ummm classnames imo should be used for like logic of determineing the class to apply if none then no need to use it here.... just for future refernce and this is mostly my opinion

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/MeetingHeader/MeetingHeader.jsx
> +          {/* <div className="status">{t(getRelativeTimeLocKey())}</div> */}
ive seen this commented out multiple places, will we be needing it or can we remove it?

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/MeetingView/AgendaView/AgendaGroups.jsx
> +              {/* <span className="expansionIconStatus"><StatusInProgress className={buildIconClass(active, next, completed)} /></span> */}
can we remove instead of commenting out? beauty of git is we always have a trace to pull the code back from

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/MeetingView/MeetingView.scss
> +  // display: flex;
lets remove instead of commenting out

2023-08-11 00:18 UTC, JMStudiosJoe commented on frontend/src/components/MeetingView/MeetingView.scss
> +    margin-left: calc(1rem + 10px); // match AgendaGroup styling
good comments

2023-08-11 00:29 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.jsx
> +      <div
awesome - thanks!

2023-08-11 00:32 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.jsx
> +            value.value.toLowerCase().split(" ").join("-"),
absolutely agree - I coincidentally felt the same and iterated/refactored this in my latest PR so that the specific styles per dropdown selection are not derived via this logic but instead passed as a property in the props object  -- see [commit](https://github.com/codeforsanjose/project-happening-atm/pull/337/commits/ed5c34f5dbe5f634f6cf53c0affea530307621da)

2023-08-11 00:33 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.scss
> +		overflow: hidden; // ensure rounded edges
yes definitely.  Pardon the wording, my comments are to indicate this ensures the rounded edges are visible without any background.  if the overflow is not hidden then there is a layer behind it.

2023-08-11 00:34 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.scss
> +		// border:1px solid $pendingBlueBackground;
Agreed - thanks for your review and patience!  Appreciate the feedback and will update accordingly!

2023-08-11 00:35 UTC, jerrycyip commented on frontend/src/components/MeetingView/AgendaView/AgendaGroups.jsx
> +              {/* <span className="expansionIconStatus"><StatusInProgress className={buildIconClass(active, next, completed)} /></span> */}
Agreed - thanks for your review and patience! Appreciate the feedback and will update accordingly!

2023-08-11 00:36 UTC, jerrycyip commented on frontend/src/components/MeetingView/MeetingView.scss
> +  // display: flex;
Will update

2023-08-11 00:38 UTC, jerrycyip commented on frontend/src/components/MeetingHeader/MeetingHeader.jsx
> +    <div className={classnames("meeting-header")}>
Oh yes, totally agree! Sorry I got a little carried away at the end and must have applied it everywhere without confirming necessity.

2023-08-11 00:38 UTC, jerrycyip commented on frontend/src/components/MeetingView/MeetingView.scss
> +    margin-left: calc(1rem + 10px); // match AgendaGroup styling
Thanks!

2023-08-11 20:34 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.scss
> +		overflow: hidden; // ensure rounded edges
pardon the spacing issue - fixed my linter and will re-push with proper indent spacing (2 spaces)

2023-08-11 20:36 UTC, jerrycyip commented on frontend/src/components/Dropdown/Dropdown.scss
> +		// border:1px solid $pendingBlueBackground;
quick side note: I added this particular comment only because the MVP designs did not cover expected behavior for this scenario. That said, hopefully it's self-explanatory enough.

2023-08-11 20:54 UTC, jerrycyip commented on frontend/src/components/Dropdown/Panel.jsx
> +/*
I see your point.  I wasn't sure if it was necessary either - if it's okay with you I'd like to remove it in the next PR just to minimize merge conflicts when I pull down this PR back into my local.

2023-08-11 20:59 UTC, jerrycyip commented on frontend/src/components/MeetingHeader/MeetingHeader.jsx
> +          {/* <div className="status">{t(getRelativeTimeLocKey())}</div> */}
agreed - removed

2023-08-11 21:31 UTC, jerrycyip commented
Per Joey's review have updated code with suggested changes and repushed.  Note, as per github conversations above, I will look to combine the (un-necessary) Panel abstraction in the next PR (337) into the parent Dropdown component instead.  In addition, the extraneous logic to extract the css styling per meeting status in the Dropdown component has been addressed in the already created [Commit](https://github.com/codeforsanjose/project-happening-atm/pull/337/commits/ed5c34f5dbe5f634f6cf53c0affea530307621da) in the next PR 337.

2023-08-15 00:34 UTC, JMStudiosJoe approved these changes

2023-08-15 01:40 UTC, merged