Update meeting agenda item status
codeforsanjose/project-happening-atm pull request #337
Opened 2023-08-10 22:04 UTC by jerrycyip

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
In line with latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=5537-109157&mode=design&t=b8Spb17FnUVyw5Ku-0), update Meeting Agenda Item Status selection functionality for admins to implement re-usable dropdown from prior [PR 336](https://github.com/codeforsanjose/project-happening-atm/pull/336), deprecate redundant code and refresh styling to match designs.

- Describe what changes are being made
In line with latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=5537-109157&mode=design&t=b8Spb17FnUVyw5Ku-0), update Meeting Agenda Item Status selection functionality for admins to implement re-usable dropdown from prior [PR 336](https://github.com/codeforsanjose/project-happening-atm/pull/336), deprecate redundant code and refresh styling to match designs.

- Describe why these changes are being made
Following best practice, frontend components such as the admin dropdown selector should be re-usable whenever possible (e.g. DRY code = don't repeat yourself).  Updates to styling and functionality also align with latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=5537-109157&mode=design&t=b8Spb17FnUVyw5Ku-0)

- List the use cases and edge cases relevant to this PR
Updates to styling and functionality also align with latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=5537-109157&mode=design&t=b8Spb17FnUVyw5Ku-0)

- Describe how errors will be handled. How will we know if this code breaks in production
N/A - functionality tested before/after code changes for any errors

- Describe any external libraries/dependencies added or removed in this PR
N/A

- Describe any security risks are there regarding this change
N/A

- Describe how you tested these changes
  * Functionality tested before/after code changes for any errors
  * Note, the MVP designed confirmation modal that is shown after updating the meeting status will be included in a later (hopefully next) PR submission. That modal functionality calls for the creation of a new re-usable confirmation modal that can be re-used across different confirmation use cases. Upon reviewing the existing code base, there currently appears to be multiple modal components implemented all doing slight variations of the same thing (not good).

- Link to relevant external documentation
Updates to styling and functionality also align with latest [MVP designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=a2t3EN7Iytj0m7dP-0) and [MVP Components](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=5537-109157&mode=design&t=b8Spb17FnUVyw5Ku-0)

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

Admin user:
https://github.com/codeforsanjose/project-happening-atm/assets/54079796/1d3690b8-3812-481b-b5ad-c17927e28934

Community User:
![mtg_agenda_item_status_before community_user](https://github.com/codeforsanjose/project-happening-atm/assets/54079796/19b22d01-34d1-444d-be06-4930f59ef74e)

#### After

Admin user:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/129de4e2-d39f-43ac-81cd-49493c691596

Community User:

![mtg_agenda_item_status_after community_user](https://github.com/codeforsanjose/project-happening-atm/assets/54079796/479ce9e6-290a-41d5-b614-a253dfa3cd54)

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2023-08-10 22:25 UTC, jerrycyip reviewed
for some reason github is showing backend/graphql_api/graphql/resolvers/mutation.js as a new file, but it's the same file as before.  I tried adding a comment and re-pushing the file, but it appears to show the same git tracking issue (6575da9 above).  I think the real issue is the ci / build errors for AWS below?

2023-08-15 22:03 UTC, jerrycyip commented on frontend/src/components/MeetingView/AgendaView/AgendaView.jsx
showCompleted no longer in scope as per latest MVP designs - hence removed

2023-08-16 02:52 UTC, jerrycyip commented on frontend/src/components/MeetingListView/MeetingListView.jsx
apologies, I think the majority of the 'differences' for MeetingListView.jsx are actually just the linter applying auto-formatting upon save.

2023-08-17 23:42 UTC, JMStudiosJoe commented on backend/graphql_api/graphql/resolvers/mutation.js
> +      const isAdmin = await authentication.verifyAdmin(dbClient, email_address); // local dev hack: change to true for admin user creation
awesome

2023-08-17 23:45 UTC, JMStudiosJoe commented on frontend/src/components/Footer/Footer.jsx
> +            href="https://www.codeforsanjose.org/"
this needs to be www.opensourcesanjose.org now

2023-08-17 23:45 UTC, JMStudiosJoe commented on frontend/src/components/Footer/Footer.jsx
> +            <img className="CFSJ" src={CFSJ_Logo} alt="Code for San Jose" />
but can keep the nameing here hhe he he

2023-08-17 23:49 UTC, JMStudiosJoe requested changes
small change rquests and great job!

2023-08-17 23:49 UTC, JMStudiosJoe commented on frontend/src/components/Footer/Footer.scss
> +  z-index: 5000; // allow admin agenda item dropdown to sit on top
i never like the huge number so far i think this is 1 of like 4 so far so only need to keep it max under 100

2023-08-18 01:15 UTC, jerrycyip commented on frontend/src/components/Footer/Footer.scss
> +  z-index: 5000; // allow admin agenda item dropdown to sit on top
yeah, the large numbers see excessive to me as well.  I can definitely lower it and resubmit.  Thanks for the review and feedback!

2023-08-18 01:50 UTC, jerrycyip commented on frontend/src/components/Footer/Footer.jsx
> +            href="https://www.codeforsanjose.org/"
Noted - will update.  Thanks!

2023-08-18 04:19 UTC, jerrycyip commented on frontend/src/components/Footer/Footer.jsx
> +            <img className="CFSJ" src={CFSJ_Logo} alt="Code for San Jose" />
Sounds good. Once we have new logo images handy, I can update this in a future PR.

2023-08-18 04:25 UTC, jerrycyip commented on frontend/src/components/Footer/Footer.scss
> +  z-index: 5000; // allow admin agenda item dropdown to sit on top
Per suggestions, I have reviewed all z-indexes above >10, and have updated values as follows:
Index.js: (instance of z-index w/ old value of) 10000 -> 60 (new value)
Dropdown.scss: 10000 -> 50
NavbarHeader.scss:9999 -> 50
footer.scss: 5000 -> 40
Subscribe.scss:  3000 ->  30
Search.scss:  1001 -> 20
meetingHeader.scss: 100 -> 10

2023-08-22 23:44 UTC, JMStudiosJoe commented on frontend/src/components/Footer/Footer.jsx
> +            <img className="CFSJ" src={CFSJ_Logo} alt="Code for San Jose" />
lets have it as another pr to just update the logo, no worries to have here

2023-08-22 23:45 UTC, JMStudiosJoe commented on frontend/src/index.scss
> +  z-index: 60;
omg yes so much easier hahahahahah OVER 9000?!?!

2023-08-22 23:45 UTC, JMStudiosJoe approved these changes

2023-08-22 23:46 UTC, merged