Poll meeting updates
codeforsanjose/project-happening-atm pull request #350
Opened 2023-11-02 22:10 UTC by jerrycyip

### :scroll: Description
Poll/sync for meeting and agenda item status updates

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
  - This PR implements syncing functionality using interval polling logic from the client in order to check for any meeting and agenda item status updates made by other admin users.  This new functionality ensures users see the latest information when interacting with the application.

- Describe what changes are being made
  - This PR implements syncing functionality using interval polling logic from the client in order to check for any meeting and agenda item status updates made by other admin users.  This new functionality ensures users see the latest information when interacting with the application.
  - In evaluating the appropriate implementation of these changes, three different approaches were considered: (i) server sent events (SSEs), (ii) polling the database for updates, (iii) RT updates via web sockets (e.g. Apollo GraphQL "subscription" functionality). Intermittent polling of the database per approach approach no. 2 was ultimately chosen for a variety of reasons and factors:
    - Given the concurrent user base for Happening ATM will largely be limited to just a sub-segment of the city of San Jose, as opposed to needing to scale to hundreds of thousands or millions of users, the increased load polling represents should hopefully be manageable.
    - Although Server Sent events were perhaps the most elegant solution, finding proven and readily implementable design patterns and examples suitable for our project and technology stack (e.g. Apollo, GraphQL, React etc) proved too challenging at least in the near term. To elaborate, because Server Sent Events are not readily supported by Apollo, a new library (e.g. graphql-over-sse etc.) would need to be implemented. In addition, this approach also represents setting up another backend server. Considering the existing challenges standing up QA and higher environments, there were reservations with introducing yet another server. Furthermore, there are concurrent connection limitations (6-8 max) with server sent events over http1 versus http2 which supports virtually unlimited number.
    - Apollo GraphQL "Subscriptions" over websockets was not implemented considering this required implementing another protocol (websockets) and potentially introducing complications with firewall restrictions for users.  Whereas websockets are a proven approach for applications such as real-time chat or messaging, it appears to be overkill for this use case.

- Describe why these changes are being made
  - Without these changes, ATM users would not see real-time updates to the meeting and agenda item statuses unless they continually refreshed the page manually (poor user experience).
   
- List the use cases and edge cases relevant to this PR
  - This functionality align with requirements and use cases as outlined in the [MVP Design wireframes](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=V9ykb2o7fzl3dOCe-0)

- Describe how errors will be handled. How will we know if this code breaks in production
  - N/A Prior to these changes, users were unaware of status changes as there were no updates on the frontend client without the user manually refreshing the page.

- Describe any external libraries/dependencies added or removed in this PR
  - N/A

- Describe any security risks are there regarding this change
  - N/A

- Describe how you tested these changes
  - Performed testing across different browsers (Chrome, Firefox, Edge, Safari) to confirm consistent and expected behavior post changes as described above.

- Link to relevant external documentation
[MVP Design wireframes](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=V9ykb2o7fzl3dOCe-0)
Work also described per recent [ATM outstanding requirements tracking spreadsheet](https://docs.google.com/spreadsheets/d/1qC3KXiR7IqV4OKp1k9P3w-Pb3xC8K0CWQevPhtFt0Vw/edit#gid=0) - see item "A0010"

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before
Behavior before changes for 3 separate users (2 admins and 1 community user) on 3 different browsers. Notice statuses don't change automatically and require manual refresh:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/8aa6a687-269a-4460-b294-0a90d006566d

#### After
Behavior after change for 3 separate users (2 admins and 1 community user) on 3 different browsers. Notice meeting status and agenda item status update automatically now:

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/63ba3ee8-5cfd-4484-8041-8e2115cda89f

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2023-11-07 02:33 UTC, JMStudiosJoe requested changes

2023-11-07 02:33 UTC, JMStudiosJoe commented on frontend/src/components/MeetingListView/MeetingListView.jsx
> +    }, 20000);
lets assign a cont value with a defined amount ex : FIVE_MIN_IN_MILISECONDS kinda thing for no magic numbers.

2023-11-07 02:33 UTC, JMStudiosJoe commented on frontend/src/components/MeetingListView/MeetingListView.jsx
> +    }, 20000);
could this also pay attention to a parent value and change values when that value changes? this could potentially become expensive if on many meetings. Instead of a timer, maybe a useEffect on an incoming prop?

2023-11-07 02:33 UTC, JMStudiosJoe commented on frontend/src/components/MeetingView/MeetingView.jsx
> +  console.log('data:', data);
lets remove the logs please

2023-11-07 02:33 UTC, JMStudiosJoe commented on frontend/src/components/MeetingView/MeetingView.jsx
> +    const timer = window.setInterval(() => {
same here for magic number below :)

2023-11-09 22:20 UTC, jerrycyip commented on frontend/src/components/MeetingListView/MeetingListView.jsx
> +    }, 20000);
Appreciate the review!  I've made the following changes per your suggestions
- Created a constants file
- Increased the polling interval by 50% (20 to 30 seconds) to try to address potential load
- consulted with SJ City Council calendar to check about number of monthly meetings, and it doesn't look to be more than 10 a month (e.g at most 2x a week): https://sanjose.legistar.com/DepartmentDetail.aspx?ID=21676&GUID=ACCCCFF5-F14A-4E1A-8540-9065F45A8A90
- In addition, per conversation with Ellina at last week's HackerDojo meeting, share clarified there was a prior decision to replace the view for past meetings with just a link to city of SJ past meetings so this main page (corresponding to MeetingListView) would only be current and future meetings on this main page
- Investigated possibility of paying attention to a parent value, however this is challenging given this is the main page of the application such that there are no props passed nor any that could logically be added and tracked for the purposes of this functionality (i.e. updating meeting status changes). Happy to discuss further.

2023-11-09 22:21 UTC, jerrycyip commented on frontend/src/components/MeetingView/MeetingView.jsx
> +  console.log('data:', data);
apologies I missed this! removed = )

2023-11-09 22:22 UTC, jerrycyip commented on frontend/src/components/MeetingView/MeetingView.jsx
> +    const timer = window.setInterval(() => {
Updated with a constants value and increased the polling interval here by 33% as well.

2023-11-12 00:07 UTC, JMStudiosJoe approved these changes

2023-11-12 00:08 UTC, merged