Add city council mtg zoom link URL
codeforsanjose/project-happening-atm pull request #351
Opened 2023-11-07 01:31 UTC by jerrycyip

Per business owner clarifications added configurable constant to use as default zoom url link for city council meetings:
'https://sanjoseca.zoom.us/j/88471470054'

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
  - Per business owner clarifications added configurable constant to use as default zoom url link for city council meetings:
'https://sanjoseca.zoom.us/j/88471470054'

- Describe what changes are being made
  - Per business owner clarifications added configurable constant to use as default zoom url link for city council meetings:
'https://sanjoseca.zoom.us/j/88471470054'. As part of the changes also removed the button element tag which was originally inside of the zoom url anchor tag as this is poor practice from a non-semantic HTML perspective and is likewise not good for accessibility (A11) purposes. To retain the same design, I instead applied the button styling to the zoom anchor tag itself.  In addition, I fixed the anchor tag's styling such that the clickable area of the anchor tag only extends up to the width of the element instead of the entire width of the container (see short video below for demo of before/after).

- Describe why these changes are being made
  - See above

- List the use cases and edge cases relevant to this PR
  - See above

- Describe how errors will be handled. How will we know if this code breaks in production
  - N/A

- Describe any external libraries/dependencies added or removed in this PR
  - N/A

- Describe any security risks are there regarding this change
  - N/A

- Describe how you tested these changes
  - Tested before and after changes in front-end browser.
 
- Link to relevant external documentation
  - latest changes are per latest [MPV designs](https://www.figma.com/file/MEBv8hZLr4MICzKCVXADjg/Happening-ATM?type=design&node-id=6150-89385&mode=design&t=GyIvU6lZ6z8VY5bX-0)

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/457af7ec-820a-4aa1-8dbc-fe6e7c7b0e59

#### After

https://github.com/codeforsanjose/project-happening-atm/assets/54079796/0247e8bc-856f-49da-a843-3cbec0983335

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2023-11-12 00:12 UTC, JMStudiosJoe requested changes
Updating to env car would be best if possible at this time, if not let me know in response to comment here please.

2023-11-12 00:12 UTC, JMStudiosJoe commented on frontend/src/constants/MeetingZoomURL.js
> +const MeetingZoomURL = {
Let's add to the env vars that way easier to update if needed

2023-11-15 21:06 UTC, jerrycyip commented on frontend/src/constants/MeetingZoomURL.js
> +const MeetingZoomURL = {
Appreciate the review and suggestion! Accordingly, I've moved this to an environment variable as per latest commit: "1fca7278601741cf38ad9f51d6e959845d21d9bb".  It took some trial and error before I remembered that create-react-app requires environment variables to have a prefix "REACT_APP_" so I also added a comment in the environment file as a reminder.

2023-11-16 14:21 UTC, JMStudiosJoe approved these changes

2023-11-16 14:22 UTC, merged